name: Python package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run core tests (excluding UI tests)
        run: |
          pytest --maxfail=1 --disable-warnings \
            --ignore=tests/test_pipeline_ui.py \
            --ignore=tests/test_pipeline_ui_additional.py \
            --ignore=tests/test_pipeline_ui_variants.py
