
name: Python Package CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t maya-pipeline-tool .

      - name: Run tests inside container
        run: |
          docker run --rm \
            --entrypoint bash \
            maya-pipeline-tool \
            -lc "xvfb-run --auto-servernum \
              --server-args='-screen 0 1280x1024x24' \
              pytest --maxfail=1 --disable-warnings -q --cov=src"
