name: Python package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies for headless Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgl1-mesa-dri libglu1-mesa libxrender1 libxext6

      - name: Setup environment variables for headless Qt and software rendering
        run: |
          echo "DISPLAY=:99" >> $GITHUB_ENV
          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV
          echo "LIBGL_ALWAYS_SOFTWARE=1" >> $GITHUB_ENV

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 &

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage using xvfb-run, ignoring UI tests
        run: |
          xvfb-run -a pytest --maxfail=1 --disable-warnings -q --cov=src --cov-report=xml --cov-report=term-missing \
            --ignore=tests/test_pipeline_ui.py \
            --ignore=tests/test_pipeline_ui_additional.py \
            --ignore=tests/test_pipeline_ui_variants.py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
